### ISSUE TITLE
not connect and show error

### ISSUE THREAD

**Issue by masiiha** [rrva/openconnectui2#2]
createToolXRemoteService got error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named se.rrva.OpenConnectUI2.ToolX was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named se.rrva.OpenConnectUI2.ToolX was invalidated: failed at lookup with error 3 - No such process.}

**Comment by rrva** [comment]
1. Which MacOS version? 
2. Which OpenConnectUI2 version?

Get some logs

1. Quit OpenConnectUI2 
2. In a terminal run the following to capture some logs:

```
sudo log stream --process se.rrva.OpenConnectUI2.ToolX > ToolX.log
```

3. Start OpenConnectUI2, try to connect

4. Quit the log stream by pressing `Ctrl+C` 

5. Get launchd logs for the privileged helper:

```
grep se.rrva.OpenConnectUI2.ToolX /private/var/log/com.apple.xpc.launchd/launchd.log > ToolX_launchd.log
```

Attach the files ToolX.log and ToolX_launchd.log (maybe review so that they do not contain any sensitive information)

**Comment by rrva** [comment]
Closed due to inactivity
